project:
  type: book
  output-dir: docs

book:
  title: "Manuel pratique de recherche documentaire"
  subtitle: "Pour le séminaire PLU6058"
  author:
      - name: "Pascal Martinolli"
        orcid: "0000-0003-0122-5300"
        affiliations:
          - name: "Université de Montréal"
            department: "Bibliothèques / UdeM"
  date: "2024-03-13"
  language: "fr"
  license: "CC-BY-NC-SA 4.0"
  pdf-url: "https://bib.umontreal.ca/multidisciplinaire/plu6058"
  status : "living document"
  type: "book"
  version: "4.1"
  abstract: "Ce manuel est principalement conçu pour accompagner le séminaire PLU6058, qui vise à améliorer les compétences informationnelles des étudiant.es des cycles supérieurs de l'Université de Montréal. Cependant, il peut également être utilisé de manière autonome et autodidacte pour la recherche et l'utilisation de la documentation dans le cadre d'un projet de recherche. En outre, il peut être utilisé comme une ressource éducative par les enseignant.es en bibliothèque de recherche."


  chapters:
  - index.qmd
  - part: chapters/introduction.qmd
    chapters:
    - chapters/identitenumerique.qmd
    - chapters/preparation.qmd
    - chapters/zoteroinstaller.qmd
  - part: chapters/phaseexploratoire.qmd
    chapters:
    - chapters/zoterocollecter.qmd
    - chapters/sourcestertaires.qmd
    - chapters/principauxcourants.qmd
  - part: chapters/phaserecherche.qmd
    chapters:
    - chapters/recherchemotcle.qmd
    - chapters/rechercheliste.qmd
    - chapters/recherchebdd.qmd
    - chapters/rechercheautres.qmd
    - chapters/parcoursrecherche.qmd
  - part: chapters/phaselectureanalyse.qmd
    chapters:
    - chapters/zoteroorganiser.qmd
    - chapters/alertes.qmd
    - chapters/evaluer.qmd
  - part: chapters/phaseredaction.qmd
    chapters:
    - chapters/citer.qmd
    - chapters/zoterorediger.qmd
  - part: "Au-delà de votre recherche : méthodes"
    chapters:
    - chapters/sauvegardedurable.qmd
    - chapters/identifierdocument.qmd
    - chapters/cahierrecherche.qmd
    - chapters/operateurs.qmd
    - chapters/formats.qmd
    - chapters/numerisation.qmd
    - chapters/archivage.qmd
    - chapters/revuelitterature.qmd
    - chapters/kitdepartudem.qmd
  - part: "Au-delà de votre recherche : outils"
    chapters:
    - chapters/markdown.qmd
    - chapters/obsidian.qmd
    - chapters/thesaurus.qmd
    - chapters/cartographieinformation.qmd
    - chapters/terminalbash.qmd
    - chapters/zoteroplus.qmd
    - chapters/llm.qmd
  - part: "Au-delà de votre recherche : diffusion"
    chapters:
    - chapters/droitdauteur.qmd
    - chapters/micropublication.qmd
    - chapters/prepublication.qmd
    - chapters/bloguersarecherche.qmd
    - chapters/microbloguer.qmd
    - chapters/communicationparaffiche.qmd
    - chapters/libreacces.qmd
    - chapters/editeurpredateur.qmd
    - chapters/retraction.qmd
    - chapters/bibliometrie.qmd
    - chapters/oupublier.qmd
    - chapters/promouvoir.qmd
    - chapters/gestiondonneesrecherche.qmd
    - chapters/wikipourlarecherche.qmd
  - part: "Annexes"
    chapters:
    - chapters/notehistorique.qmd
    - chapters/enseignantenbib.qmd
    - chapters/contributions.qmd
    - chapters/bibliographie.qmd
    - chapters/glossaire.qmd
    - chapters/accesdroits.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    geometry:
      - inner=2cm
      - outer=2cm
      - top=2cm
      - bottom=2cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded


