# Archivage {#sec-archivage}

-   Préalables : Suivez TOUTES les indications de :

    -   La section Stratégies de [sauvegarde durable](#sec-sauvegardedurable)

    -   Et du chapitre sur les [formats](#sec-formats)

-   Le support **électronique est instable et fragile**. Au-delà de quelques années, ne faites pas confiance aux disques durs, ni aux CD gravés ou aux DVD gravés, ni aux clés USB.

    -   Règle "3-2-1" des archivistes : 3 copies de tout, 2 copies sur des infonuages différents et 1 copie à la maison.

    -   Si vous avez des fichiers électroniques, déplacez-les d'un support à un autre tous les 3 ans.

    -   Disques électroniques : Ne les laissez pas inutilisés plus d'un an. Protégez-les de l'humidité, de la chaleur et des chocs. Les disques SSD (smartphones, laptop récents) : Ne devraient pas rester sans l'alimentation de leur batterie pendant longtemps.

    -   Les CD/DVD gravés : Gravez vos données sur un CD ou DVD de temps en temps. Protégez-les de l'humidité, de la chaleur, de la lumière, des rayures, de certains feutres marqueurs, des étiquettes collées et des doigts. Préférez les disques argentés ou dorés (pas les bleutés). Préférez les boitiers (pas les pochettes souples). Gravez en vitesse normale et vérifiez la gravure.

-   **Imprimez** vos documents importants et conservez-les dans un lieu d'**entreposage durable**.

    -   Une photocopie imprimée sur du [papier non acide](https://fr.wikipedia.org/wiki/Papier_non_acide) peut durer au moins 40 ans (à l'abri de la lumière, de humidité, loin de tout plastique PVC, et sans colle).

    -   N'oubliez pas de sélectionner et d'imprimer vos feuilles de paie, documents d'assurance, photos de mariage, de naissance, vos poèmes de jeunesse, vos articles, et tout ce que vous avez rédigé et qui a de la valeur pour vous.

    -   Ayez un plan d'archivage personnel : 

        -   Identifiez ce que je veux archiver :

            -   Ce que j'ai créé (texte, images, films montés, etc.) et qui entraînerait un choc émotionnel intense en cas de perte.

            -   Mes documents administratifs numérisés (taxes, paies,\...).

            -   Les plus importants (paies, contrats, actes notariés,\...) doivent aussi être imprimés.

            -   Ma correspondance (courriels) et ma liste de contacts.

            -   Ce que j'ai capturé ou téléchargé (photos, vidéos, bookmarks, références Zotero, captures Evernote, ebooks,\...).

            -   Mes listes de musiques, de films, de livres,\... (la plupart sont retrouvables facilement, alors une liste devrait suffire).

        -   Sélectionnez les plus importants/ les meilleurs.

        -   Organisez la sélection.

        -   Faites des copies sur des supports multiples, pérennes (papier si possible), à différents endroits.

        -   Gérez le contenu de temps en temps (vérifiez).

    -   Entreposez durablement : 

        -   Dans un local à température constante, peu humide, sur l'avant-dernière étagère du haut de votre bibliothèque.

        -   Dans une boîte en carton ; ou mieux dans une boite en plastique Coroplast (mais surtout pas en PVC) ; ou dans des grandes pochettes Ziplock sans PVC ;

        -   Astuce pour enlever l'humidité dans des contenants fermés : sachets de gel de silice.
