# Outils de cartographie de l'information {#sec-cartographieinformation}

## De quoi parle-t-on ?[^cartographieinformation-1]

[^cartographieinformation-1]: Ce chapitre a été originellement rédigé en 2022 par une équipe de bibliothécaires de la BLSH de l'UdeM : Émilie Dalpé, Pascal Martinolli, David Patenaude et Mathieu Thomas. Il a été édité et augmenté par Pascal Martinolli, 2024.

-   Depuis quelques années, plusieurs plateformes proposent des services en ligne de repérage et de visualisation de la littérature universitaire. On appelle souvent ces outils des *literature mapping tools* ou encore des *smart literature finders*.
-   Ces plateformes sont principalement basées sur les données de citation en accès libre comme CrossRef, OpenCitation et autres.

## Pourquoi sont-ils intéressants ?

-   Les principales fonctions de ces services sont :
    -   « De compléter des revues de littérature avec des documents qui auraient pu nous échapper » ;
        -   Bien que cette fonction soit mise en avant par ces outils, nos expérimentations n’ont pas remarqué que ces outils avaient repérés des documents qui avaient échappé à une solide revue de littérature classique par mots-clés. Ces outils peuvent parfois nous paraître un peu redondants à nous, bibliothécaires, mais ils semblent être très appréciés par certains usagers moins expérimentés..
        -   Hypothèse (non-vérifiée) : ces outils permettraient de repérer des documents de méthodologie pertinents n’utilisant pas des mots-clés de la revue de littérature.
    -   De valider la revue de littérature que nous avons déjà rassemblée ;
    -   De visualiser le graphe de citation de la littérature sélectionnée ;
        -   Pour mieux contextualiser chaque élément et pour mieux l’évaluer.
        -   Pour hiérarchiser l’engagement à avoir par rapport à la littérature sélectionnée (quelle étude lire en premier, etc.).
    -   De s’initier de manière pratique aux notions de données liées, de graphes de citation, de données de citation ouvertes, aux identifiants pérennes, etc.

## Biais

-   Les recherches dans ces outils sont très inégales selon les disciplines, voire même selon les sous-disciplines.
-   Les documents avec DOI et les documents de langue anglaise sont sur-représentés.
-   Parfois ces outils ne repèrent pas les documents récents car les données de citation ne sont pas intégrées régulièrement.
-   Il y a globalement peu de transparence dans les algorithmes de recommandation des articles (« *similar articles* » , etc.) donc peu de reproductibilité et peu de prédictibilité des résultats. Autre manque de transparence : il faut chercher un peu pour connaître la composition du corpus documentaire de ces outils.
-   Il peut y avoir des changements soudains de modèle économique qui changent les modalités d’accès à certains outils. Certains peuvent même être fusionnés avec d’autres ou disparaître. Cela nous oblige à faire veille sur ce que l’on compte recommander.
-   En raison des fonctions de repérage et de visualisation, il peut y avoir un « effet gadget » que certains chercheurs vont apprécier et que d’autres vont rejeter.

## Suggestions d'outils

Il existe une grande variété d’outils offrant parfois des fonctionnalités très différentes et originales.

### [Litmaps](https://www.litmaps.com/)

-   À partir d’un article ou d’un ensemble d’articles, créer une carte (seed map) constituée d’une liste de références.
-   Créé par une petite entreprise néo-zélandaise en 2016.
-   Nécessite de se créer un compte (gratuit en février 2023). Litmaps Free permet d’entrer 20 “input articles”. Litmaps Pro (10\$/mois) donne accès à un nombre illimité de recherches.
-   Basé sur les graphes de citations de: OpenAlex, Crossref and Semantic Scholar Academic Graph. Seulement les éléments avec des DOI.
-   Une séquence d’utilisation typique :
  -   Créer un nouvel espace de travail (Workspace) puis une nouvelle carte (Map). Débuter la nouvelle carte avec un article ou un ensemble d’articles.
  -   Litmaps créé une nouvelle carte avec des suggestions.
      -   Décocher les articles non-pertinents pour les faire disparaître de la carte (à partir du menu-liste en bas à droite, cocher x).
      -   Cliquer sur l’onglet Explore et ajouter de nouveaux articles (à partir du menu-liste en bas à droite, cocher +).
      -   Alterner entre les onglets Map et Explore pour améliorer votre sélection.
  -   Lorsque satisfait, exporter votre sélection au format BibTeX vers votre logiciel bibliographique.

### [Inciteful.xyz](https://inciteful.xyz/)

-   Considéré comme un outil de type *Smart Literature Finder*.
-   Créé par Michael Weishuhn, un entrepreneur anglais, depuis 2020.
-   Pas besoin de créer un compte, accès ouvert et libre (février 2023).
-   À partir d’un article ou d’un ensemble d’articles, permet de repérer des références qui citent les mêmes sources (*Similar Papers*) et de repérer des références très citées ou incontournables (*Most Important Papers in the Graph*) ou la distance entre deux articles (et le chemin).
-   Les *similar papers* tendent à être plus récents, les most important papers tendent à être plus anciens.
-   Fonctionne de deux manières:
  -   On recherche un article de départ (*seed paper*) pour se construire un réseau de références, histoire de trouver la littérature la plus pertinente;
  -   On sélectionne deux articles pour voir comment la littérature les connecte.
-   Basé sur les graphes de citations de : OpenAlex, Crossref, OpenCitations, Semantic Scholar Academic Graph.

### [CitationTree](https://www.citationtree.org/)

-   Explorer l'essentiel d'une bibliographie et de son arbre de citations à partir du DOI d'un article source.
-   Basé sur le graphe de citations de Crossref et Semantic Scholar.
-   Soumettre le DOI d'un article pertinent et générer l'arbre de sa bibliographie.

### [ResearchRabbit](https://www.researchrabbit.ai/)

-   À partir d'un article ou un ensemble d'articles, augmenter la collection de vos résultats pertinents en repérant qui les a cité et quels sont leurs bibliographies, leurs auteurs, etc.
-   Se créer un compte.
-   Créer une nouvelle collection de référence avec *New Collection.*
-   Ajouter un ou plusieurs articles dans cette collection avec *Add Papers*. Possibilité d'ajouter des documents en lot au format BibTeX ou RIS.
-   Augmenter la collection avec les options : 
  - *Similar papers* (bof), 
  - *All references* (ce qui a été cité en bibliographie des documents de la collection : pas mal), 
  - *All Citations* (les documents qui ont cité les documents de la collection : pas mal), 
  - *These Authors* (les autres publications des auteurs des documents de la collection : pas mal).
-   Recommencer encore et encore. Des vues graphiques en réseau sont utilisables.
-   Synchronisable avec Zotero.

## Logiciels de visualisation

-   Les logiciels de visualisation bibliométriques tels que VosViewer ou CiteSpace sont principalement destinés à visualiser de grands corpus existants et non pas à repérer de la littérature.
-   Ils permettent d'avoir une vue d'ensemble sur un corpus déjà constitué. Ils peuvent être utiles lorsqu'on veut débroussailler un sujet et faire ressortir des réseaux de termes, de revues ou d'auteurs importants.
-   En général, les outils sont difficiles à manipuler et des compétences en bibliométrie sont parfois nécessaires pour comprendre les éléments à paramétrer.
-   Typiquement, vous avez déjà un ensemble de plusieurs centaines de références, vous les exportez dans un logiciel comme VOSviewer et vous paramétrer les visualisations pertinentes.

### [VOS Viewer](https://www.vosviewer.com/)

- À installer. Paramétrage complexe. Fonctionnalités en développement constant.

### [ZoteroRnalysis](https://github.com/pmartinolli/ZoteroRnalysis)

-   Un code informatique dans le langage R qui permet d’analyser votre bibliothèque de références et de produire des graphiques ou des tableaux de données. Vous pouvez ainsi avoir une vue synthétique et une meilleure représentation de l’ensemble de vos références. Dans le cas présent, ce code va utiliser une extraction de votre bibliothèque Zotero sous la forme d’un fichier csv et il va produire des graphiques en pdf et des tableaux en csv : les auteurs, les maisons d’édition ou les revues les plus mentionnés, les marqueurs les plus utilisés et répartis dans le temps, voire la distribution du nombre de pages de mémoires et de thèses.
-   Pour bien fonctionner, il faut que votre bibliothèque de références soit bien indexée, qu’elle ait une certaine cohérence et qu’elle ait un certain volume (plusieurs centaines de références sur un sujet).
-   Il existe une fonctionnalité supplémentaire qui utilise le logiciel OpenRefine pour aller enrichir des données à partir de données existantes dans Wikidata. À partir d’une série d’institutions, il est par exemple possible d’aller chercher le pays de celles-ci dans un processus qui s’appelle “la réconciliation de données”. Pour le moment, ce processus n’est pas expliqué dans le code.
-   [ZoteroJSnalysis](https://observablehq.com/@pascaliensis/zoterojsnalysis) : Une version plus facile d’utilisation est disponible en javascript sur la plateforme ObservableHQ. Sans rien installer, un utilisateur peut s’y créer un compte, dupliquer le code et y verser sa bibliothèque (à la vue de tous avec un compte gratuit).

