#  Citer sans plagier {#sec-citer}

-   **Citer** ou **référencer/sourcer** Ce chapitre s'appuie partiellement sur Thomas, Mathieu. « Citations, références et plagiat. Formation de mise à niveau : étudiants à la maîtrise ». Université de Montréal, septembre 2020 et sur Croteau, Marc-Olivier, Myrian Grondin et Pascal Martinolli. « Citer ses sources ». Université de Montréal, septembre 2021.?

    -   Dans la définition classique et grand public, **citer** (*quotation*) c'est reprendre un extrait des mots exacts d'un auteur.

    -   Citer veut aussi dire **référencer/sourcer** (*citation*, *reference*), c'est à dire indiquer la source d'une idée, d'un propos, d'une information factuelle, d'un extrait de mots exacts d'un auteur, etc. Quand nous allons parler de citer, c'est ce sens-là qui sera privilégié.

        -   « Je pense donc je suis. »

##  Pourquoi citer ?

-   Dans la recherche, on cite principalement :

    -   **Pour faire comprendre sur quelles sources on s'appuie.**

    -   **ET pour permettre vérifier facilement dans ces sources.**

-   C'est grâce à ça que l'édifice de la connaissance scientifique mondiale se construit et se consolide au fil des siècles.

    -   Allégorie : les découvertes ce sont les briques de l'édifice, les citations c'est le mortier qui fait tenir le tout ensemble.

-   Autres raisons :

    -   Pour faciliter la **compréhension** de votre travail, votre lecteur saura distinguer vos idées de celles des personnes mentionnées.

    -   Pour donner le **crédit** à l'auteur original des propos et des idées qui ne sont pas les nôtres.

    -   Pour payer sa « **dette littéraire** », une expression de littérature où un auteur reconnaît ses influences.

    -   Pour rendre **hommage**.

    -   Pour des raisons **légales**

        -   Par exemple, avec une licence CC-BY il faut mentionner la source.

        -   Important : même un document dans le domaine public, donc qui n'a pas besoin d'être cité légalement, doit être cité éthiquement dans un travail de recherche.

    -   Pour étaler son **érudition** et montrer tout ce qu'on a lu.

    -   Pour déclarer des **conflits d'intérêt** ou des **liens d'intérêts**.

    -   Pour montrer qu'on fait partie du **club** d'une école de pensée (signalement de loyauté) ou pour s'inscrire en **filiation** par rapport à des idées.

    -   Pour éviter d'être accusé de **plagiat** et d'en subir les conséquences dramatiques pour vos études ou votre carrière de chercheur : perdre des points sur vos travaux, échouer un cours, ou être renvoyé de l'université.

-   Autres raisons (non éthiques) :

    -   Pour renvoyer l'ascenseur à des collègues qui vous ont cité.

    -   Pour obéir à une revue scientifique peu scrupuleuse qui vous demande d'ajouter quelques références pour booster ses indicateurs bibliométriques de citation.

    -   etc J'étudie les pratiques de citations dans les jeux de rôle sur table, pour en savoir plus : <https://jdr.hypotheses.org/878>.

-   Seule exception : pas la peine de citer ce qui est de **notoriété publique**.

    -   Les faits simples à vérifier (date de naissance, l'eau boue à 100°C, etc.).

    -   Les définitions simples et non discutées (exemple : « Molìère est un dramaturge français du XVIIe siècle »).

    -   Si vous pensez que votre lecteur a besoin de vérifier ou d'aller plus loin : citez une source.

    -   Il est possible qu'un document rédigé pour une discipline n'ait pas les mêmes conditions de notoriété publique dans une autre discipline.

##  Éviter le plagiat

-   **Plagier, c'est laisser croire qu'on est l'auteur d'un travail, qui est en réalité le travail de quelqu'un d'autre.**

    -   Il y a très peu d'ambiguité dans cette définition.

    -   «Travail» = idée fixée dans un document ou non-fixée (discours ou cours prononcé) de 1000 page ou d'une phrase. Même les idées qui ne sont pas sous droit d'auteur.

    -   «Laisser croire» = pas citer, mal citer, citer incomplètement, citer avec mauvaise foi, citer faussement, etc.

-   Autre définition : Plagier, c'est utiliser le travail d'autrui, **sans donner une attribution appropriée** <https://www.plagiarismtoday.com/2023/02/16/the-definition-of-plagiarism/>.

-   Exemples :

    -   Reproduire un texte/idée d'une autre personne **sans mentionner** cette personne (et implicitement faire croire que ce texte/idée est de soi-même). C'est la forme la plus courante de plagiat.

    -   **Mal citer**

        -   Citer de manière **imprécise** : ne pas indiquer la page ou le document exact, quand on connaît cette information.

        -   Citer de manière **incomplète** : on choisit de ne citer qu'une partie des travaux ou des travaux mineurs d'un auteur.

        -   **Déformer** le travail d'autrui : citer avec **mauvaise foi,** interpréter autrui et lui faire exagérer son propos ou les déformer.

        -   Citer **faussement** : faire dire à un auteur l'inverse de ce qu'il a dit.

        -   **Invisibiliser** : sur-représenter un travail pour en invisibilier un autre

    -   **Reproduire ou transformer** des images ou des morceaux d'image sans indiquer la source.

    -   **Faire exécuter** votre travail par une autre personne (*contract cheating*) ou par un *LLM* comme ChatGPT.

    -   **Auto-plagiat** (voir plus loin)

    -   Travailler en équipe sur un travail dont l'évaluation est individuelle sans que le professeur est été avisé de ce travail commun.

-   Le plagiat doit être distingué de la contrefaçon ou des aspects juridiques Commentaire de PrPissenlit : <https://www.youtube.com/watch?v=91G8UN7UTQ0&lc=Ugzxf819Wt8bLr-IDPB4AaABAg>. Il peut y avoir plagiat sans poursuite pénale.

    -   Exemple : paraphraser une recette de cuisine trouvée ailleurs et la publier sur son blogue. C'est du plagiat, même si légalement on a le droit. Dans le cadre universitaire, c'est condamnable.

-   Dans le contexte de la recherche et de l'université, le plagiat est condamné car :

    -   Il cache ou nie le travail de recherche fait auparavant. Aussi infime soit-il.

    -   Il empêche de connaître les travaux sur lesquels un travail se base.

    -   Il empêche de repérer les sophismes et les arguments fallacieux (exemples : aucune source ou sur mauvaises sources).

### Solution : savoir quand citer

-   Quand citer ?

    -   Pour **chaque argument** présenté dans un travail : ajouter au moins une source.

        -   Pour chaque citation exacte rapportée mot à mot.

        -   Pour chaque paraphrase.

        -   Pour chaque donnée (graphique, tableau, chiffre, image, etc.).

    -   Pour chaque bout de code importé dans son code source : indiquer la source.

    -   Montrer votre originalité en combinant, comparant, expliquant, contextualisant, critiquant les arguments et les sources utilisés.

        -   Sinon votre travail va être un polichinelle / *patchwork* / monstre de Frankeinstein, sans substance.

-   Recommandations :

    -   Attention à l'aspect quantitatif : 1 argument non cité dans un travail de 1000 page : toujours du plagiat, quel que soit sa proportion.

    -   Citer, même si la source utilisée n'a jamais été publiée.

    -   Citer, quel que soit la forme de la source : document imprimé, électronique ou discours prononcé.

    -   Citer, quel que soient les droits d'auteur du document : du copyright complet au domaine public.

    -   Reconnaître qu'on est influencé constamment par les informations que nous absorbons Vidéo de Viviane de Sci+ *À partir de quand c'est du plagiat ?* <https://youtu.be/91G8UN7UTQ0>.

    -   Diversifier ses sources.

    -   Remonter à la source originale brute plutôt que de réutiliser des synthèses/ reprises/ commentaires.

    -   Ne vous appropriez pas un style d'une autre personne

    -   Laisser décanter loin des documents originaux :

        -   Dans le contexte d'une création artistique ou conceptuelle ou pratique : si vous voulez créer un travail original, commencez par rédiger le premier brouillon ou le plan sans consulter d'autres sources (consultées dans un second temps) Vidéo de Viviane de Sci+ *À partir de quand c'est du plagiat ?* <https://youtu.be/91G8UN7UTQ0>.

        -   Dans le contexte d'un travail universitaire : laisser du temps puis rédiger votre paraphrase sans consulter le document original. Vérifiez ensuite dans un second temps. Et citez la source!

##  Choisir son style

-   Il existe plusieurs manières de présenter les citations courtes, longues, abrégées et la bibliographie finale.

    -   Ces règles de présentation sont appelées « styles bibliographiques ».

    -   Les logiciels de gestion bibliographiques comme Zotero ou Endnote font souvent de 80 à 100% ce travail.

    -   Il en existe plusieurs milliers mais une dizaine sont très populaires.

-   Il y a trois grandes familles de style :

    -   les **styles (auteur-date)** :

        -   populaires en sciences sociales

        -   idéal pour repérer rapidement la source avec le nom des premiers auteurs

        -   les plus connus et utilisés à l'UdeM sont les styles :

            -   *APA*

            -   *Chicago auteur-date.*

    -   les **styles notes de bas de page**

        -   populaires en sciences humaines

        -   idéal pour de longues sources commentées en bas de page

        -   le plus connu et utilisé à l'UdeM est le style :

            -   *Chicago notes de bas de page*

            -   Il y a aussi le style *LLuelles* ou *McGill* en droit.

    -   les **styles numérotés**

        -   populaires en santé et en sciences naturelles

        -   très lisibles mais on ne peut y mentionner la page

        -   le plus connu et utilisé à l'UdeM est le style : *Vancouver*.

    -   Parfois le département demande un style particulier, parfois c'est votre direction de recherche, parfois vous avez le choix.

    -   Une fois choisi, vous conservez le même style dans tout le document (sauf pour une thèse par article où chaque partie peut avoir un style différent).


##  Comment citer ?

1.  Choisir un **style bibliographique** ou suivre le style bibliographique imposé pour son travail.

2.  Repèrer **une source** sous la forme d'un document, qui contient **une idée** intéressante à incorporer dans son travail.

3.  Choisir comment on veut **incorporer cette idée** :

    -   Avec avec une **paraphrase** ou un **résumé** :

        -   Reprendre dans vos mots à vous une idée, ou un ensemble d'idées complexes, exprimées dans la source.

        -   C'est la manière recommandée par rapport aux citations exactes.

            -   Dans un travail de recherche universitaire, vous allez plus souvent paraphraser que faire des citations exactes.

            -   Pour faciliter la lecture, car le passage s'intègre au style de reste de votre texte.

            -   Pour présenter l'idée de l'auteur de façon plus condensée qu'au moyen de la citation directe.

            -   Pour vérifier sa compréhension des propos d'un auteur.

        -   Comment rédiger une paraphrase :

            -   Utiliser des synonymes pour remplacer des termes (certains termes très génériques sont difficiles à remplacer : monde, science, etc.)

            -   Changer la structure de la phrase, utiliser le style direct ou indirect, etc.

        -   Attention :

            -   Rédiger une paraphrase sans mention de la source est du plagiat, parfois nommé paraplagiarisme (*paraplagiarism*).

            -   Changer quelques mots ici et là en conservant le même canevas de phrases que l'auteur n'est pas de la paraphrase. C'est une citation exacte maquillée.

            -   Traduire mot à mot un énoncé d'une autre langue n'est pas de la paraphrase. C'est une citation exacte.

            -   Reprendre les mots exacts d'une source, mais sans mettre de guillemets, est considéré comme du plagiat (même si vous mettez la référence à la source) <https://integrity.mit.edu/handbook/academic-writing/avoiding-plagiarism-paraphrasing>.

    -   Ou avec une **citation exacte**

        -   À utiliser de manière parcimonieuse dans quelques cas précis seulement :

            -   Pour appuyer ses propos ou son hypothèse d'une manière spécifique.

            -   Pour présenter une position que l'on va ensuite commenter et critiquer.

            -   Pour reprendre une formulation particulièrement heureuse ou intéressante, dont l'essence serait perdue si on la paraphrasait.

        -   Mettre l'extrait « entre guillemets dans le texte en reproduisant exactement le texte original »

        -   S'il y a des erreurs dans le texte original ou des idées outrageantes, vous pouvez mettre `(sic)` ce qui veut dire *sic transit gloria mundi* (= « ainsi passe la gloire du monde » = Oh lala, c'est du grand n'importe quoi!).

        -   Si vous voulez sauter une partie non pertinente pour raccourcir la citation, remplacez la partie par `(...)` ou` ``[``...``]`

        -   **Citation exacte et courte** (moins de 3 lignes) : à insérer dans le texte en continu.

        -   **Citation exacte et longue** (plus de 3 lignes) : créer un mini paragraphe avec une mise en page différente : simple espacement entre les lignes, décalages à droite et à gauche.

4.  Juste après avoir incorporé cette idée sous une des 3 formes, ajouter une **citation abrégée** (on dit aussi appel de citation) selon le style bibliographique choisit :

    -   une mention de type (auteur, date)

    -   un numéro de note de bas de page en exposant + une note de bas de page correspondante contenant la référence complète.

    -   un numéro simple (parfois entre parenthèse ou entre crochet ou en exposant)

5.  Si le document original fait plus de 50 pages, c'est une bonne pratique d'indiquer **à quelle page** ou à quel intervalle de pages vous avez trouvez l'information.

    -   Dans le cas d'une citation est exacte (courte ou longue), cela peut être obligatoire avec certains styles.

    -   Les styles numérotés ne gèrent pas les pages. Seuls les styles (auteur-date) et notes de bas de page savent gérer les pages citées.

6.  Bonification de la citation : Quand vous incorporez une idée dans vos travaux, quel que soit sa forme, si possible :

    -   Ajoutez quel est son contexte, la discipline d'où elle provient, son étendue, sa méthode et ses limites.

    -   Ajoutez comment cette idée s'articule avec les autres idées que vous avez incorporer Cela évitera de faire des documents de type Polichinelle ou Frankeinstein avec plein d'idées prises de partout et mélangées n'importe comment..

7.  À la **fin du document**, dans une section nommée « Bibliographie » ou « Liste des références », vous listez :

    -   selon l'ordre du style bibliographique,

    -   la sélection de toutes les citations abrégées mentionnées dans le texte,

    -   sous la forme de **citations complètes**.


## Savoir identifier un document

Voir @sec-identifierdocument 


## Document inaccessible ou partiel

-   Si une source B est mentionnée dans un document A que vous avez entre les mains, et si vous voulez reprendre l'idée exprimée :

    -   Il faut **faire** **tout votre possible** pour aller repérer et lire le document B.

        -   C'est une des bases de la recherche documentaire.

        -   Ne faites pas confiance au document A pour avoir retranscrit fidèlement ou exactement les idées de B À ce sujet, je vous invite à lire l'article « L'histoire de la note de bas de page mortelle » qui parle du manque d'éthique de ne pas aller vérifier la source soi-même et des dizaines de milliers de morts qui peuvent en être la conséquence à <http://www.slate.fr/story/147105/medecine-100-mots-tuer-en-medecine>.

    -   « Oui mais, si je ne peux pas \[c'est dans une langue que je ne maîtrise pas, dans un manuscrit unique d'un monastère en haut d'une montagne, gardé par des moines récalcitrants\] »

        -   Alors vous allez citer la source B, mais **uniquement dans le texte** (ou dans une note de bas de page).

        -   Vous n'allez **pas citer la source B en bibliographie finale** ou Liste des références

            -   Car à cet endroit devraient se trouver uniquement des documents que vous avez lu au complet.

-   Si vous n'avez lu qu'un chapitre dans un livre (parce que vous avez eu besoin de ce chapitre uniquement) :

    -   Ne citez pas le livre au complet en bibliographie finale.

    -   Citez **uniquement le chapitre** en bibliographie finale.

        -   Il y a une manière spécifique pour citer un chapitre (qui est différente de la manière de citer un livre).

##  Bibliographie finale et liste de références

-   « Bibliographie finale » ou « Liste des références » :

    -   Les deux sont des listes de références bibliographiques **complètes**.

    -   Qui correspondent à la **sélection** de toutes les citations abrégées mentionnées dans le texte.

    -   Leur but :

        -   Montrer **en un clin d'oeil** les sources utilisées par l'auteur du travail.

        -   Donner assez d'informations détaillées pour **retrouver** facilement les sources.

-   Une légère différence :

    -   Les « **liste de références** » (*list of references*) sont une **sélection stricte**. Tout ce qui s'y trouve est mentionné au moins une fois dans le texte.

        -   Dans certaines disciplines et/ou dans certains types de documents, il n'est pas possible de faire des bibliographies. Il est seulement possible de faire des listes de références (donc tout ce qui est listé doit être utilisé dans le texte).

    -   Les « **bibliographie** » (*bibliography*) peuvent contenir des **références bibliographiques supplémentaires**, qui n'ont pas été mentionnées dans le texte mais qui ont aidé à la compréhension du sujet.

##  Auto-plagiat

-   *Self-plagiarism, autoplagiarism*

    -   « Vamos à la plagiat ! » Titre d'un chapitre de *Ça tourne mal ! L'histoire méconnue et tumultueuse du cinéma français* de Philippe Lombard, 2019. Édition La Tengo.\... Non, ce n'est pas aller en auto à la plage.

-   C'est quand on fait **un travail** et qu'on reçoit **deux récompenses**. Exemples :

    -   Je fais un travail pratique (TP) et je le soumets dans deux cours universitaires différents.

    -   Je conduis une étude et je rédige ses résultats de manière quasiment identiques et je les soumets à deux revues révisées par les pairs différentes.

-   C'est une sorte de « fraude de recyclage » où on ressert un document que l'on a déjà utilisé ailleurs.

-   Le nom est proche de celui du plagiat et il est traité avec le même rejet dans la communauté de la recherche. Cependant, ce n'est pas la même chose.

-   Notez que pour publier autre chose que des recherches originales, c'est une pratique tout à fait normale dans plusieurs contextes. Par exemple, dans le contexte de l'industrie ou de l'éducation il est tout à fait normal de réutiliser des présentations, des exercices, etc.

##  Fausses citations

-   On dit aussi **citation apocryphe** pour faire plus chic.

-   Souvent attribuée à Einstein ou à des chercheurs renommés qui n'ont jamais dit ce qu'on leur attribue.

-   Ne commencez pas un travail avec une fausse citation car tout de suite on va repérer que vous n'avez pas vérifié vos sources. Même si le reste de votre travail est excellent.

##  Droit d'auteur et citation

-   Le droit d'auteur n'a rien à voir avec l'**obligation éthique de bien citer** dans le monde de la recherche.

    -   Exemple : si une œuvre est dans le domaine public (CC0), on peut l'utiliser comme on le souhaite MAIS il faut tout de même la citer dans un travail universitaire pour respecter l'éthique de la recherche et le droit d'auteur moral.

-   Bien citer permet de respecter l'aspect moral du droit d'auteur mais, dans le cas d'une diffusion de votre recherche, cela ne suffit pas car il y aussi un aspect **patrimonial** au droit d'auteur (ie. les droits liés à l'utilisation).

    -   Si votre travail est diffusé, soyez attentif à ce que toutes les parties dont le droit d'auteur ne vous appartient pas n'enfreignent pas les droits d'auteur d'autres personnes ou institutions les détenant :

        -   portions de texte,

        -   graphiques,

        -   schémas,

        -   photographies,

        -   tableaux,

        -   données, etc.

    -   Voir p. .

-   Rappel : Ce manuel est rendu disponible à des fins d'information uniquement et ne constitue d'aucune manière un avis juridique.
