# Si vous êtes enseignant.e en bibliothèque

-   Ce manuel peut être utilisé comme feuille de route ou document de base **pour monter une formation** ou un cycle de formations.

-   Recommandation pour vous approprier le contenu : **choisissez-vous un sujet de recherche** Exemples : un thème de vos disciplines qui vous est cher ou émergent, ou un hobby qui vous passionne, ou un engagement associatif que vous aimeriez prendre, etc. . Ce thème sera votre sujet d'exercice pratique pour toutes les parties de ce guide.

    -   Effets émergents potentiels :

        -   Explorer à fond les méthodes et les outils

            -   Comme si vous êtiez revenu sur les bancs de l'université et ainsi comprendre les écueils rencontrés par les étudiant.es.

            -   Exercer régulièrement ces méthodes avec plus de motivation.

        -   Explorer à fond votre sujet André-Georges Haudricourt disait « N'importe quel objet, si vous l'étudiez correctement, toute la société vient avec. ». En effet, je pense qu'il est bénéfique d'étudier en profondeur n'importe quel sujet..

        -   Combiner créativement des domaines inédits pour développer une identité personnelle distincte, voire un expertise sur un sujet Exemple: j'ai combiné une passion personnelle des jeux de rôle sur table avec ma passion professionnelle des pratiques de citation <https://github.com/pmartinolli/OtSoCG>. <https://www.psychologytoday.com/us/blog/how-do-life/202103/combining-your-interests>. De plus, je partage une base de données Zotero de documents universitaires sur le sujet <https://www.zotero.org/groups/446523/>, deux blogues en français [https://jdr.hypotheses.org/ ](https://jdr.hypotheses.org/%20)et en anglais [http://zotrpg.blogspot.com/ ](http://zotrpg.blogspot.com/%20)s et un hashtag Twitter #ScholarlyTTRPG avec lequel je diffuse une veille régulière sur le sujet..

-   Merci de contribuer en nous envoyant vos expériences, commentaires et critiques.