# Markdown : balisage léger pour la recherche {#sec-markdown}

## Pourquoi apprendre le Markdown 

- C'est extrêmement simple.
- C'est une méthode de balisage de texte lisible par les humains et par certains logiciels qui sont capables ensuite de :
  - Faire de belles visualisations du fichier
  - Exporter vers d'autres formats (html, pdf, MS Word,...)
- C'est devenu une sorte de standard dans beaucoup de domaines de la recherche.

## Quels sont les codes de balisage minimum à connaître ?

- Les balisages de niveaux de titre
- Faire des liens URL
- Faire des listes à puces ou numérotées
- Faire des gras et des italiques


## Exemples de logiciels qui utilisent Markdown 

### Obsidian pour prendre des notes

-   Voir [Obsidian.md](#sec-obsidian)


### Zettlr pour rédiger

-   [Zettlr](https://www.zettlr.com/) : Logiciel simple, permettant de rédiger au format Markdown et ensuite, en fournissant une bibliographie au format .bib (BibTeX) et un style bibliographique au format .csl, de produire différents formats de documents (PDF, html, etc.).


### Quarto pour rédiger et diffuser

-   Ce manuel a été conçu avec l'extension [Quarto](https://quarto.org/), installée dans le logiciel de statistique [RStudio](https://posit.co/download/rstudio-desktop/). Quarto a remplacé les projets RMarkdown et RBookdown.

-   Il permet de rédiger au format Markdown.

    -   Avec des références issues de Zotero.

    -   Avec un système de renvois entre sections.

    -   Avec la possibilité d'exécuter du code R ou autre pour faire des graphiques ([exemple](https://pmartinolli.github.io/JDR50bibliometrie/)).

    -   Qui peut générer en un (1) clic : un site web, un fichier PDF, un fichier Word et un fichier ePub.

        -   Le site web peut ensuite être envoyé facilement sur GitHub.io (en 3 clics).


## Autres systèmes utilisant Markdown

- [ObservableHQ](https://observablehq.com/user/@pascaliensis) pour produire de belles infographies
- Documenter les codes sources de [GitHub](https://github.com/pmartinolli) 
