# Promouvoir votre recherche {#sec-promouvoir}

### Pourquoi promouvoir votre recherche ?

-   Pour avoir un **effet à la marge** en cas de candidature égale (carrière, financement, etc.), ou pour se démarquer d'une masse de candidats.
-   Pour faciliter l'**investigation** que d'autres pourraient faire sur votre nom.
-   Pour lever l'**ambiguïté** sur votre nom si plusieurs le partagent.
-   Pour prolonger vos démarches de **vulgarisation scientifique**.

### Comment promouvoir sa recherche

-   Définir ses objectifs.
    -   Être capable de changer d'objectifs (modifier, annuler, etc.). Exemples :
        -   Commencer avec un pseudonyme, puis révéler son nom quand on est sûr de soi.
        -   Commencer à bloguer pour ses pairs et ensuite décider de bloguer plutôt pour le grand public.
        -   Commencer à micro-bloguer, puis arrêter ou mettre en pause.
-   Documenter sa démarche.
    -   Consigner ses login/ mots de passe dans un carnet de recherche.
    -   Souligner les éléments importants.
        -   Exemples : tel billet de blogue, nombre de tweets de veille rediffusés dans l'année, telle affiche à telle conférence vue par tant de personnes, etc.
        -   Peut-être les valoriser en les ajoutant à son CV ? ou à une demande de financement ?
-   Mesurer ses objectifs de temps en temps :
    -   Coût (temps, finance, etc.)
    -   Bénéfices (capital symbolique, plaisir, etc.)
    -   Risques (voir section [Risques](#sec-bloguersarecherche)).

### Prendre soin de son identité numérique

[Voir](#sec-identitenumerique) 

### Bloguer sur sa recherche

[Voir](#sec-bloguersarecherche)

### Relayer sa recherche sur Twitter ou Mastodon

[Voir](#sec-microbloguer)

### Communiquer par affiche dans un événement

[Voir](#sec-communicationparaffiche)

### Créer une série de baladodiffusion

-   Les Bibliothèques UdeM offrent des formations [Créez votre première baladodiffusion](https://bib.umontreal.ca/formations/calendrier).
-   [Guides](https://creanum.notion.site/Production-audiovisuelle-328dadbef0a74fadadaefa32fc8b77c2) et [CreanUM](https://hackmd.io/@creanum/balado).

### Créer des capsules vidéo

-   Les Bibliothèques UdeM offrent des formations en [montage](https://bib.umontreal.ca/formations/calendrier) et des studios d'[enregistrement](https://bib.umontreal.ca/travailler/espaces/creation-numerique/studio-enregistrement) et de [montage](https://bib.umontreal.ca/travailler/espaces/creation-numerique/studio-edition-numerique).

### Rédiger un article de vulgarisation dans la revue *DIRE* de l'UdeM

-   Le FICSUM propose aux étudiants de cycles supérieurs inscrits à l'UdeM de publier des articles de vulgarisation scientifique dans la revue [*DIRE*](https://www.ficsum.com/dire/).
-   Il n'y a pas de révision par les pairs, mais c'est un bon moyen de diffusion relativement accessible à tous et toutes.
-   La rédaction offre des prix aux auteurs.trices.

### Faire des micro-publications ou des prépublications

[Voir](#sec-micropublication)
