# Autres types d'outils de recherche 

##  Conversation scientifique après publication

-   Avec **PubPeer** <https://pubpeer.com/> : pour repérer les fraudes, les problèmes de méthodes, les biais, les limites, etc.
-   Avec les ***altmetrics*** (voir @sec-bibliometrie)
-   Dans les sites de microbloguing comme X/Twitter, ou Mastodon, ou BlueSky(voir @sec-microbloguer)
-   En cherchant le titre complet de l'article entre guillemets carrés dans **Google**.
-   En utilisant un **index de citations** pour savoir qui a cité cette publication.

## Littérature grise

-   La littérature grise (ou *grey literature*, ou *gray literature*) est un terme qui désigne toutes les publications qui se font en parallèle des circuits de publications commerciaux et universitaires classiques.
-   La littérature grise peut être difficile à trouver car elle se trouve dans des bases de données ou des sites web très différents.
-   Parfois, elle change d'emplacement, ou bien elle disparaît après quelques années, ce qui la rend encore plus difficile d'accès.
-   La qualité des littératures grises varie beaucoup.
-   Elle comprend :
    -   Les **rapports** (*reports*) ;
    -   Les **documents de travail** (*working papers*) avant leur publication dans une revue par comité de lecture ;
        -   Déposés dans des dépôts de *preprints.* (voir @sec-prepublication)
        -   Déposés sur le site web personnel d'un chercheur.
        -   Déposés dans un site de colloque ou de congrès, etc.
    -   Les **publications gouvernementales** ou non-gouvernementales (*government documents*). Voir ci-dessous.

### Publications gouvernementales ou non-gouvernementales

-   Les organismes qui peuvent les produire sont :
    -   des agences gouvernementales ou non gouvernementales,
    -   des entreprises,
    -   des associations,
    -   des centres de recherche,
    -   des départements universitaires, etc.
-   En général, le niveau d'objectivité est plus discutable que pour une publication universitaire.
-   Parfois les moteurs de recherche des sites gouvernementaux ne sont pas très performants : faire des recherches simples.
-   Souvent, le lien qui mène au document change ou disparaît : faire des copies personnelles et les archiver dans son logiciel de bibliographique comme Zotero; archiver une sauvegarde dans Internet Archives est aussi une bonne idée.
-   Pour votre information : il peut exister différents types de « couleurs » de livres :
    -   Un **livre blanc** (*white paper*) est un recueil d'informations et de recommandations concises sur un sujet complexe.
    -   Un **livre vert** (*green paper*) est un rapport officiel contenant des propositions qui seront discutées pour établir une politique.
    -   Un **livre bleu** (*blue book*) est un recueil de données factuelles chiffrées sur un sujet (rapport annuel, statistiques, etc.).
    -   Il existe d'autres types de couleurs de livre (rose, rouge, orange, etc.) dont les définitions et les usages varient selon les pays.

## Dépôts de prépublications (*preprints*)

Voir @sec-prepublication

## Documents d'archives

-   Chaque institution d'archives a son propre système de classement, d'indexation (imprimé ou électronique).
-   Demander plus d'information à l'archiviste (étendue du fond, accès, indexation, consultation, numérisation, etc.).

## Données numériques

-   Moteurs de recherche de qualité variable pour les repérer selon les institutions.
-   Des **micro-données** servent à construire des **données statistiques** qui servent elles-mêmes à construire des **indicateurs**.
-   **BIB+ :** Ne pas hésiter à contacter la bibliothécaire en charge des données statistiques <https://bib.umontreal.ca/guides/donnees-statistiques-geospatiales/donnees-statistiques>.

### Indicateurs

-   Données numériques **très synthétiques** sur des thèmes très larges (exemples : taux de chômage, etc.).
-   Habituellement facilement accessibles : encyclopédies, site web, documents officiels, etc.

### Données statistiques

-   Données **agrégées** selon des thèmes variés.
    -   qui ont subi un traitement statistique.
    -   rassemblées selon des critères pré-établis (exemple : taux de chômage des femmes de la région métropolitaine de recensement de Montréal entre 1960 et 2020).
    -   présenté de façon à pouvoir être interprétées (exemple : tableaux, histogrammes, etc.).
        -   Tableurs simples : Excel, Beyond20/20, LibreOffice Calc, etc.
        -   ou tableaux mis en page pour MS Word, MS Publisher, etc.
-   Accessible auprès d'institutions diverses (OCDE, etc.) et d'institutions de statistiques spécialisées (Statistique Canada, Institut de la statistique du Québec, etc.)
-   Enjeu : il faut trouver le bon groupement de données selon ses besoins. Parfois, ces données aggrégées n'existent pas. Il faut alors les construire soit même avec des micro-données.

### Micro-données ou données d'enquête

-   Données **brutes** :
    -   Peu de traitement statistique :
        -   Normalement, chaque enregistrement est **pondéré**.
        -   Possible anonymisation des données. On distingue alors le « fichier maître » dont l'accès est très restreint, au « fichier public anomymisé » (exemple : le FMGD ou fichier de microdonnées à grande diffusion, du CIQSS).
    -   Pas d'agrégation car chaque enregistrement décrit une entité (une personne, une entreprise, etc.).
-   Offre le plus de possibilités mais aussi demande le plus de travail statistique (avec des logiciels spécialisés : R, SPSS, Stata, etc.)
-   Accessibles auprès d'institutions de statistiques spécialisées : Statistique Canada, Institut de la statistique du Québec, CIQSS, etc.
-   Format (voir @sec-formats) :
    -   Un fichier de données brutes (souvent au format ASCII) de plusieurs milliers de lignes.
    -   Un fichier-clé pour l'importer dans un logiciel spécialisé.
    -   Des fichiers d'accompagnement décrivant les données.
-   Type de données :
    -   Données transversales (état à un instant *t*)
    -   Données longitudinales (suivi d'individus sur le temps)

### Données de recherche

-   Toutes les données sélectionnées ou produites dans le cadre d'une recherche.
-   De plus en plus accessibles :
    -   Mouvement du Open Data avec le dépôt de données de recherche dans des plateformes dédiées : Borealis, OSF, Zenodo, etc.
    -   Aussi parfois via l'option *Supplementary documents* de certains articles scientifiques publiés Souvent il est indiqué « Données disponibles sur demande » mais une étude de 2022 a montré que seul 7% répondaient favorablement\...<https://doi.org/10.1016/j.jclinepi.2022.05.019>.
-   Voir @sec-gdr pour gérer votre plan de données de recherche.
