# Outils de recherche de type « Listes » {#sec-rechercheliste}

## Sections bibliographiques de votre documentation

-   Il s'agit d'utiliser les **bibliographies** et les références des documents déjà repérés pour en trouver d'autres.
    -   Cette méthode est parfois appellée *snowballing* ou *pearl growing* dans le jargon des bibliothécaires.
-   Pourquoi ?
    -   Une bibliographie, c'est la **liste** de tous les documents utilisés pour un travail.
    -   C'est une mine d'or d'informations qui ont été **sélectionnées** par l'auteur.
    -   Parfois, on y trouve des documents très **difficiles d'accès** car ils ne figurent pas (ou ils sont mal indexés) dans des bases de données ou des collections en ligne.
    -   C'est la meilleure **stratégie alternative** aux recherches par mot-clé.
    -   Les références bibliographiques sont un peu comme le **« réseau social » des documents**. Découvrez qui cite qui et pourquoi...
-   Comment ?
    -   Une bibliographie est située **à la fin** d'un document.
    -   Savoir identifier une référence bibliographique : Il est important de savoir décrypter en un coup d'oeil si une référence bibliographique est un livre, un article de périodique, une partie de document (un chapitre par exemple), etc.
    -   Voir @sec-identifierdocument

### Bibliographies sélectives dans les entrées d'ouvrages de référence

-   Commencez par parcourir les bibliographies des ouvrages de référence trouvés dans la phase exploratoire (articles d'encyclopédies spécialisées, *handbook of*..., bibliographies, etc.).

### Références mentionnées dans les articles de revue de littérature

-   Pourquoi ?
    -   Les articles de revue de littérature (*article review, systematic review, meta analysis*,...) sont des rassembleurs et des attracteurs de citations.
-   Comment ?
    -   En consultant la bibliographie d'un de ces articles, repérez les documents cités.
    -   Avec un index de citation ou un outil de cartographie de l'information (voir ci-dessous), repérez les articles plus récents qui les citent.

## Sections : table des matières et index

-   Ce sont des références « internes » à un document.
-   **Table des matières** et/ou **sommaire**.
    -   Permet de survoler le contenu d'un document plus rapidement qu'un index.
-   **Index des sujets** à la fin d'un document pertinent.
    -   Souvent à la fin d'un document.
    -   Un index dans un document, c'est un indice supplémentaire de la qualité du livre.

## Ouvrages bibliographiques sur un sujet

-   Il existe des livres qui sont des listes bibliographiques plus ou moins complètes sur un sujet. Elles sont souvent classées de manière thématique et commentées ou annotées.

## Sites web des experts de votre sujet

-   Constituez une liste des principaux experts sur votre sujet.
-   Pour chacun, repérez sa page web personnelle, son blogue, son profil Google Scholar, son compte ORCID, son compte Twitter, son compte ResearchGate/Academia, etc.
    -   Sélectionnez les options de suivi pertinentes pour être prévenus des changements futurs (voir @sec-alertes).

## Discuter de son sujet en équipe de recherche

#### Avec votre direction de recherche

-   Bien définir votre sujet de recherche avec votre directrice ou votre directeur de recherche est une étape cruciale.
-   Préparez vos entretiens :
    -   En faisant des recherches préalables, en prenant des notes, en faisant des listes (faire toutes les étapes de la phase exploratoire).
    -   En consignant vos questions en avance.

#### Avec votre bibliothécaire disciplinaire

-   À l'UdeM, chaque discipline universitaire possède sa bibliothécaire disciplinaire <https://bib.umontreal.ca/nous-joindre/bibliothecaires-disciplinaires>. Contactez-la si ...
    -   ... vous avez une **question de recherche à approfondir**. Il va valider votre stratégie de recherche actuelle et vos mots-clés, identifier des bases de données idéales selon votre sujet, etc.
    -   ... vous avez un livre ou une ressource à **faire acquérir**, car son rôle est de développer les collections imprimées et électroniques.
    -   ... vous avez un besoin spécifique de **formation** sur un sujet. Il va vous donner un rendez-vous d'initiation ou vous orienter vers des services de formation (ateliers, webinaires, cours en ligne, etc.).
    -   ... vous voulez mieux **évaluer une source**. Il va vous aider à repérer les principaux courants de pensée dans votre discipline, vous donner des clés pour identifier ce qui est douteux, lister les critères de qualité, etc.
-   Si vous êtes en cycles supérieurs, certaines bibliothécaires peuvent vous proposer un **accompagnement** informel pendant la durée de vos études. Il existe aussi un accompagnement plus formel appelé **jumelage** pour certains programmes de doctorat <https://bib.umontreal.ca/services/jumelage-doctorant>.

#### Avec vos pairs

-   Dans les colloques, congrès, journées d'études, séminaires et conférences de votre discipline.
    -   Créer une liste des principaux événements à suivre, à assister ou à présenter.
    -   Organiser une journée d'études.
    -   Attention aux conférences prédatrices <https://coop-ist.cirad.fr/publier-et-diffuser/eviter-les-conferences-predatrices/>.
-   Vous pouvez créer vous-même votre groupe d'étude ou groupe de rédaction, avec des rencontres régulières et des temps de partage.
-   À la BLSH, un espace est à la disposition des étudiants des cycles supérieurs dans le cadre des Matinées de rédaction <https://bib.umontreal.ca/services/matinee-redaction>.
-   Certains associations comme Thèsez-vous <https://www.thesez-vous.com/> proposent des retraites de rédaction, des lieux d'étude et des activités accompagnant la recherche.
-   Réseautez, contribuez et partagez en ligne.

## Rayonnages de classement des bibliothèques

#### Explorer en personne la collection des livres imprimés de la bibliothèque

-   J'ai ma **carte étudiant** : je peux emprunter des documents imprimés dans le réseau des Bibliothèques UdeM.
    -   La carte étudiant peut aussi vous permettre d'accéder physiquement aux autres bibliothèques universitaires québécoises (et parfois à certains de leurs services).

#### Cote de classement de la Library of Congress

-   Pourquoi ? Les livres de la plupart des Bibliothèques de l'UdeM sont classés selon la classification de la Library of Congress.
-   Comment ?
    -   Il s'agit d'une convention d'écriture qui attribue une cote unique à un document en fonction de son thème principal. Elle est constituée de lettres puis de chiffres et de lettres. Exemple : GV 1469.6
        -   Corollaire : si vous avez repéré au moins un livre sur votre sujet, il y a de grandes chances pour que d'autres livres sur le même sujet soient rangés à côté sur les étagères.
        -   Bonne pratique : prenez en note les cotes de classification (ou cote de classement) habituelles de vos sujets et allez vous balader dans les rayons. Si vous avez fait la partie sur la recherche exploratoire, vous devriez déjà avoir collecté quelques cotes ou intervalles de cotes.
-   Je connais les cotes de classements de mes disciplines et mes sujets.
-   J'ai parcouru les emplacements de ces cotes dans la ou les bibliothèques du réseau UdeM.
-   J'ai parcouru les emplacements de ces cotes dans d'autres bibliothèques (Poly, HEC, UQÀM, ETS, McGill, Concordia, etc.).

#### Cote de classement Dewey

-   Dans d'autres bibliothèques (ou parfois cohabitant avec la classification de la Library of Congress), il y a une classification Dewey. C'est une classification thématique codée uniquement avec des chiffres et des ponctuations.
-   NB: il est possible que certaines bibliothèques aient leur propre système de classification. Notez cependant que c'est très souvent un système thématique donc aller fureter dans les rayons est valable.


## Sommaires de revues scientifiques

- Repérer une dizaine de revues scientifiques dans votre domaine et autour de votre sujet.
- S'abonner aux sommaires de ces revues. 



## Collections de maisons d'édition

- Repérer une dizaine de maisons d'édition dans votre domaine et autour de votre sujet.
- S'abonner aux collections pertinentes de ces maisons d'édition. 




