# Revue exhaustive de la littérature ou revue systématique ? {#sec-revuelitterature}

Cette section est une contribution de Cynthia Gagné (contributrice principale) et une adaptation des guides Synthèses des connaissances dont elle est une co-contributrice <https://bib.umontreal.ca/evaluer-analyser-rediger/syntheses-connaissances>.

## Quelques définitions 

### Revue de littérature? 

-   Une revue de littérature **présente** et évalue la documentation sur un sujet dans le but de le **situer** par rapport aux recherches antérieures ou à l'information existante <https://bib.umontreal.ca/evaluer-analyser-rediger/syntheses-connaissances/revue-litterature-recension-ecrits>.

    -   C'est une **sélection** de documents (et pas tous).

    -   La méthode est moins rigoureuse ou reproductible ou transparente que d'autres revues (voir plus loin). Deux personnes différentes pourraient arriver à une revue de la littérature très différente.

-   Elle peut prendre deux formes :

    -   Un article scientifique complet.

    -   Une partie d'un document (par exemple, une partie dans un article scientifique, dans une thèse, dans un mémoire ou dans une demande de subvention).

-   Autres noms possibles : recension des écrits, recension de la littérature, analyse bibliographique, revue narrative, synthèse de la littérature, revue de la documentation, *review*.

-   Elle peut servir à :

    -   Synthétiser et familiariser les lecteurs sur un sujet.

    -   Trouver une question de recherche originale.

    -   Acquérir le vocabulaire et les concepts liés à son problème de recherche.

    -   Identifier des méthodes et techniques de recherche qui ont déjà été utilisées pour un problème similaire.

-   Revue de littérature\... exhaustive ?

    -   Une revue de littérature est exhaustive lorsque toute la documentation pertinente est repérée.

    -   Il faudra donc faire plus de tri dans les résultats.

    -   L'exhaustivité concerne la recherche de documents et est indépendante du type de revue de littérature réalisé.

### La fameuse « revue systématique »

-   Le type de synthèse de connaissances le plus rigoureux <http://www.bandolier.org.uk/painres/download/whatis/Syst-review.pdf> :

    -   Utilise une **méthodologie très rigoureuse**, reproductible, basée sur un protocole afin de réduire la possibilité de biais. Les critères d'inclusion et d'exclusion sont transparents et déterminés en avance.

    -   Identifie **toutes les preuves** publiées et non publiées sur un sujet en particulier.

-   Travail de longue haleine, demandant beaucoup de ressources :

    -   Il faut prévoir **de 6 mois à 2 ans** pour en faire une.

    -   À faire en **équipe** (3 personnes au moins pour éviter les biais).

-   Répond à **une question précise** et peut aider à la prise de décision.

    -   Exemple : *Effects of improved street lighting on crime*

    -   Exemple : *Youth empowerment programs for improving self-efficacy and self-esteem of adolescents*

    -   Exemple : Quels sont les facteurs protecteurs associés à une stabilité résidentielle chez les personnes itinérantes qui sont passées par un refuge comparativement à celles qui n'y ont pas séjourné ?

-   Très répandu en sciences de la santé, par exemple pour déterminer l'efficacité d'un traitement ou d'une intervention.

    -   -- Les revues systématiques Cochrane sont le « *gold standard* » des revues systématiques <https://www.cochrane.org/>.

### Autres types de revues de littérature 

-   En plus des revues de littérature classiques et des revues systématiques, il existe aussi :

    -   les études de la portée (*scoping review*),

    -   les revues rapides,

    -   les *umbrella reviews*, etc.

    -   les méta-analyses.

-   Arbre de décision pour choisir la revue de littérature la mieux adaptée à votre besoin <https://bib.umontreal.ca/public/bib/gerer-diffuser/arbre-decision-syntheses-connaissances.pdf>.

## Particularités pour les sciences sociales 

-   Concepts parfois plus **difficiles à cerner**.

    -   Il faut parfois prendre le temps de nous-mêmes les définir. Par exemple : Qu'entend-on par « microagressions » ? Que veut-on inclure ?

-   Information plus **éparpillée** : plusieurs bases de données, littérature grise très diverse, etc.

-   Souvent **multidisciplinaire**.

-   Importance de chercher dans **plusieurs langues**.

## À quoi penser avant de se lancer ? 

-   **[Avoir bien absorbé et pratiqué l'essentiel des méthodes de ce manuel, au moins une année ou un semestre auparavant.]{style="color: purple"}**

-   [À quelles question ou problématique ma revue de littérature doit-elle répondre ? ]{style="color: purple"}

-   [Mon sujet est-il suffisamment précis ? Bien défini ? ]{style="color: purple"}

-   [Quel type de revue de littérature est le plus adapté ? ]{style="color: purple"}

-   [Quels sont le but et l'étendue de ma revue de littérature ? ]{style="color: purple"}

-   [Quels types de documents vais-je inclure ? ]{style="color: purple"}

-   [Quelles disciplines vais-je considérer ? ]{style="color: purple"}

-   [Est-ce que je veux être exhaustif dans ma recherche d'information ? ]{style="color: purple"}

-   [Quelles limitations vais-je appliquer à ma recherche ? Par ex. : Date de publication, types d'étude, langues, etc. ]{style="color: purple"}

-   [Existe-t-il déjà une revue de littérature sur mon sujet ?]{style="color: purple"} [voir p. ]{style="color: purple"}

## Conseils pour la recherche 

-   [Prendre rendez-vous avec votre bibliothécaire disciplinaire.]{style="color: purple"}**[ BIB+]{style="color: purple"}**[ ☐]{style="color: purple"}

-   [Plan de concepts]{style="color: purple"} [voir p. ]{style="color: purple"}[.]{style="color: purple"}

-   [Chercher dans plusieurs bases de données (listées dans les guides disciplinaires).]{style="color: purple"}

-   [Combiner plusieurs méthodes de recherche]{style="color: purple"} [voir p. ]{style="color: purple"}[ :]{style="color: purple"}

    -   [mots-clés libres]{style="color: purple"} [voir p. ]{style="color: purple"}[, ]{style="color: purple"}

    -   [descripteurs et thésaurus]{style="color: purple"} [voir p. et p.]{style="color: purple"}[, ]{style="color: purple"}

    -   [citations]{style="color: purple"} [voir p. ]{style="color: purple"}[, ]{style="color: purple"}

    -   [bibliographie]{style="color: purple"} [voir p. ]{style="color: purple"}[, ]{style="color: purple"}

    -   [méthode]{style="color: purple"} [voir p. ]{style="color: purple"}

-   [Se créer un compte dans les bases de données bibliographiques pour sauvegarder ses stratégies.]{style="color: purple"}

-   [Se créer des alertes au fur et à mesure]{style="color: purple"} [voir p.]{style="color: purple"}

-   [Être attentifs à traduire différemment les stratégies de recherche lorsqu'on interroge plusieurs base de données bibliographiques différentes. ]{style="color: purple"}

-   [NOT : à éviter lorsqu'on veut être exhaustif. ]{style="color: purple"}

    -   [Il faut mieux filtrer a posteriori pour ne rien manquer. ]{style="color: purple"}

-   [Adapter des stratégies existantes et adopter des stratégies avancées]{style="color: purple"} [p. ]{style="color: purple"}

-   [Valider sa recherche : Se baser sur les bibliographies pour vérifier si les articles déjà identifiés comme intéressants sont repérés.]{style="color: purple"}

-   [Garder des traces de ses démarches + tenir un journal de ses décisions.]{style="color: purple"}

### Littérature grise 

-   Si l'on veut être exhaustif, il est important de repérer la littérature grise pertinente <https://bib.umontreal.ca/evaluer-analyser-rediger/syntheses-connaissances/rediger-revue-systematique?tab=2826>. Celle-ci regroupe tous les documents, papier ou électroniques, qui ne sont pas contrôlés par des maisons d'édition. Par exemple :

    -   Rapports de recherche

    -   Résumés et actes de conférences

    -   Publications gouvernementales

    -   Études cliniques en cours / protocoles

    -   Prépublications

    -   Mémoires et thèses de doctorat

    -   Statistiques, etc.

-   À voir pour une typologie complète <http://www.greynet.org/greysourceindex/documenttypes.html>

-   Souvent, ces documents ne sont pas repérables avec des recherches classiques dans les bases de données.

## Outils 

-   Logiciels bibliographiques : Zotero voir p. , p. , p. , p. ou Endnote.

    -   Importer tous les résultats.

    -   Trier seulement dans le logiciel.

        -   Ne pas effacer de références (à la place : les marquer comme «rejetées»).

        -   Fusionner les doublons

    -   Créer un dossier et aussi un marqueur par importation par base de données (pour indiquer l'origine de la référence). Ainsi chaque référence garde une trace de l'origine de son repérage (voire des origines si il y a des doublons fusionnés).

-   Covidence <https://bib.umontreal.ca/evaluer-analyser-rediger/syntheses-connaissances/covidence/introduction> : Outil pour la gestion des résultats de revues systématiques, de méta-analyses, de revues de la portée, etc. utilisable seul ou en équipe.

-   Les Bibliothèques de l'UdeM offrent du support et de la formation pour ces 3 outils.
