# Astuces complémentaires pour Zotero {#sec-zoteroplus}

## Importations de références

#### Avec un identifiant ISBN ou autre

-   Prenez un livre imprimé en main et retournez-le. Normalement, s'il est récent, au-dessus du code barre se trouve un numéro d'identifiant du livre appelé ISBN.

-   Dans Zotero, cliquez sur l'icône Baguette magique (Ajouter un document par son identifiant). Saisissez l'ISBN (sans les traits d'union) puis tapez Entrée. Zotero se connecte à la Library of Congress et la BNF. Si une bibliothèque a enregistré ce livre avec l'ISBN, la notice est récupérée.

-   Ça fonctionne aussi avec d'autres identifiants uniques comme le DOI (pour les articles, certains chapitres, etc.) ou le PubMed ID ou le arXiv ID. Vive les identifiants pérennes pour faciliter l'interopérabilité (le I de FAIR) des outils de la recherche!

#### Avec un PDF reconnu

-   Vous avez déjà collecté plusieurs PDF ? Avec un peu de chance, Zotero va les reconnaître et recréer des notices.

-   Sélectionnez un ou plusieurs PDF, glissez-déposez-les dans Ma Bibliothèque. Attendez quelques instants. Si Zotero a été capable de repérer des informations clés dans le PDF, il s'est connecté en ligne pour récupérer la notice bibliographique, l'importer dans Zotero et mettre le PDF en pièce jointe. On a été chanceux.

-   Si on a moins de chance, Zotero n'a pas réussi. Le PDF reste donc tout seul dans Zotero, au même niveau que les notices. Il est inexploitable tel quel. On va faire un clic-droit dessus, choisir \]*\[Create parent document\]*\[ (Créer un document parent). Puis, saisir un identifiant si on en a un (voir précédemment) ou cliquer sur Manual pour saisir une notice à la main (voir suivant). Le PDF sera incorporé en pièce jointe de cette notice. Il sera exploitable.

#### Astuce : J'ai déjà une bibliographie rédigée

-   Comment la transformer en notices Zotero rapidement ? Option 1, s'il y a surtout des livres et des articles :

    -   Si c'est un livre, faites un copier-coller des auteurs et de quelques mots du titre dans Worldcat.org\] \[<https://www.worldcat.org/>\]\[. Il y a beaucoup de chance que vous trouviez une référence de qualité moyenne à importer avec le connecteur.

    -   Si c'est un article, faites un copier-coller des auteurs et de quelques mots du titre dans Google Scholar\] \[<https://scholar.google.com/>\]\[. Il y a beaucoup de chance que vous trouviez une référence de qualité moyenne à importer avec le connecteur.

-   Option 2 : faire séquencer sa bibliographie dans le service en ligne [AnyStyle.io](https://anystyle.io/). Ça demande un peu de clics et de réglages mais cela peut être adapté à vos besoins. [Conseils d'utilisation](https://bib.umontreal.ca/citer/logiciels-bibliographiques/zotero/ajouter-references#c75434).

-   Option 3 : utiliser un outil de type LLM. Ça demande une supervision car des erreurs s'y glissent fréquemment.

#### Astuce : Passer de Endnote à Zotero

-   Ou vice-versa : c'est possible sans perte majeure d'information (à part les groupes/collections). Il y a une petite manipulation à faire si on veut récupérer les pièces jointes <https://bib.umontreal.ca/citer/logiciels-bibliographiques/endnote/ajouter-references#c105733>.

-   Attention aux utilisateurs de Mendeley : ce logiciel propriétaire ne vous permettra pas d'exporter vos mots-clés, donc vous risquez d'être « prisonnier » de cette application si vous ne voulez pas perdre de l'information d'indexation sur laquelle vous avex travaillé.

## Ajouter une recherche vers l'outil de recherche Sofia en un clic

-   Cherche avec le titre seulement (mais on peut bidouiller le code pour chercher d'autres choses)

-   Zotero \> Parametres \> Avancés \> Ouvrir le répertoire de données : dossier Locate \> fichier engines.json. Remplacer le code par ceci <https://pastebin.pl/view/raw/2577b31b> et redémarrer Zotero.

-   Ensuite, sélectionner une ou plusieurs références et aller dans le menu de droite Localiser \> UdeM Sofia. Cela permet de rechercher dans Sofia avec le titre seulement et de sauver de 8 à 11 clics. LibKey demande trop de paramètres et donc échoue la plupart du temps quand il n'y a pas de DOI (les livres par exemple).

## Désactiver le *spellchecker* qui souligne en rouge

-   [Désactiver le correcteur](https://forums.zotero.org/discussion/19771/workaround-to-disable-spell-checker) : Paramètres (Menu Édition sous Windows/Linux ; Menu Zotero sous MacOS) \> "Avancées" \> "Éditeur de configuration". Dans la fenêtre qui s'ouvre alors, tapez extensions.spellcheck.inline.max-misspellings et changez sa valeur à 0 ou -1. Au redémarrage de Zotero, vous n'aurez plus de soulignements intempestifs.\
